apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
spec:
  # If Ingress is enabled, use ClusterIP. Otherwise, use the type from values.yaml
  type: {{ .Values.ingress.enabled | ternary "ClusterIP" .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "flask-aws-monitor.selectorLabels" . | nindent 4 }}