replicaCount: 1
image:
  repository: ste18nati/flask-aws-monitor # Change this
  tag: "placeholder" # Jenkins will update this tag
  pullPolicy: Always
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
service:
  type: LoadBalancer
  port: 5001
ingress:
  enabled: false
  className: "nginx"  # Change to match your ingress controller (nginx, traefik, istio, etc.)
  annotations: {}
  hosts:
    - host: flask-aws-app.netanelen.com  
      paths:
        - path: /
          pathType: Prefix
awsCredentials:
  accessKey: ""
  secretKey: ""
